name = "ritvik-ai-chat"
compatibility_date = "2023-05-18"

[env.production]
name = "ritvik-ai-chat"
route = "ask.ritvik.io/*"

[[env.production.routes]]
pattern = "ask.ritvik.io/*"
custom_domain = true
